name: ci

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  cli-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: Verify Bun version
        run: bun --version

      - name: Install CLI dependencies
        run: bun install

      - name: Run type check
        run: bun run typecheck

      - name: Run Biome check
        run: bun run check

      - name: Run CLI tests
        run: bun run test